/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AzureClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AzureClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AzureTenantId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Site": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "Table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}